---
- name: add docker repo
  apt_repository:
    repo: deb {{ docker_apt_url }} {{ ansible_distribution_release }} main
    state: present
    filename: docker

- name: install docker
  apt: 
    name: docker 
    state: present
    update_cache: yes

- name: cgroupdriver
  replace:
    path: /lib/systemd/system/docker.service
    regexp: '--exec-opt native.cgroupdriver=cgroupfs'
    replace: '--exec-opt native.cgroupdriver=systemd'

- name: systemd daemon-reload
  systemd:
    daemon-reload: yes

- name: add insecure-mirror
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: restart docker
