---
- name: MemTotal(KB)
  shell: grep 'MemTotal:' /proc/meminfo|awk '{print $2}'
  register: result
- set_fact: 
    CONNTRACK_MAX={{ (result.stdout | float) * 1024 / 16384 / 2 }}
    CONNTRACK_BUCKETS={{ (result.stdout| float) * 1024 / 16384 / 2 / 8 }}

- name: load modules on boot
  template:
    src: netfilter.conf.j2
    dest: /etc/modules-load.d/netfilter.conf

- name: nf_conntrack hashsize persistence
  template:
    src: netfilter_parameter.conf.j2
    dest: /etc/modprobe.d/netfilter_parameter.conf

- name: modprobe modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - nf_conntrack
    - br_netfilter

- sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - { name: vm.swappiness, value: 0 }
    - { name: fs.file-max, value: 6553600 }
    - { name: fs.aio-max-nr, value: 1048576 }
    - { name: kernel.shmall, value: 2097152 }
    - { name: kernel.shmmax, value: 4294967295 }
    - { name: kernel.shmmni, value: 4096 }
    - { name: kernel.sem, value: 250 32000 100 128 }
    - { name: kernel.sysrq, value: 0 }
    - { name: kernel.core_uses_pid, value: 1 }
    - { name: kernel.msgmnb, value: 65536 }
    - { name: kernel.msgmax, value: 65536 }
    - { name: kernel.pid_max, value: 65536 }
    - { name: net.core.rmem_default, value: 262144 }
    - { name: net.core.rmem_max, value: 4194304 }
    - { name: net.core.wmem_default, value: 262144 }
    - { name: net.core.wmem_max, value: 1048576 }
    - { name: net.core.netdev_max_backlog, value: 262144 }
    - { name: net.core.optmem_max, value: 65536 }
    - { name: net.ipv4.ip_local_port_range, value: 9000 65500 }
    - { name: net.ipv4.conf.all.send_redirects, value: 0 }
    - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
    - { name: net.ipv4.conf.all.rp_filter, value: 0 }
    - { name: net.ipv4.conf.default.rp_filter, value: 0 }
    - { name: net.ipv4.conf.default.accept_source_route, value: 0 }
    - { name: net.ipv4.tcp_syncookies, value: 1 }
    - { name: net.ipv4.tcp_max_tw_buckets, value: 6000 }
    - { name: net.ipv4.tcp_window_scaling, value: 1 }
    - { name: net.ipv4.tcp_timestamps, value: 0 }
    - { name: net.ipv4.tcp_sack, value: 0 }
    - { name: net.ipv4.tcp_rmem, value: 4096 87380 4194304 }
    - { name: net.ipv4.tcp_wmem, value: 4096 16384 4194304 }
    - { name: net.ipv4.tcp_mem, value: 94500000 915000000 927000000 }
    - { name: net.ipv4.tcp_max_orphans, value: 3276800 }
    - { name: net.ipv4.tcp_max_syn_backlog, value: 262144 }
    - { name: net.ipv4.tcp_synack_retries, value: 1 }
    - { name: net.ipv4.tcp_syn_retries, value: 1 }
    - { name: net.ipv4.tcp_tw_reuse, value: 1 }
    - { name: net.ipv4.tcp_fin_timeout, value: 30 }
    - { name: net.ipv4.tcp_slow_start_after_idle, value: 0 }
    - { name: net.ipv4.tcp_keepalive_time, value: 30 }
    - { name: net.ipv4.neigh.default.gc_thresh1, value: 80000 }
    - { name: net.ipv4.neigh.default.gc_thresh2, value: 90000 }
    - { name: net.ipv4.neigh.default.gc_thresh3, value: 100000 }
    - { name: net.ipv4.ip_forward, value: 1 }
    - { name: net.bridge.bridge-nf-call-iptables, value: 1 }
    - { name: net.bridge.bridge-nf-call-ip6tables, value: 1 }
    - { name: net.netfilter.nf_conntrack_tcp_timeout_established, value: 6000 }
    - { name: net.netfilter.nf_conntrack_tcp_timeout_time_wait, value: 30 }
    - { name: net.netfilter.nf_conntrack_tcp_timeout_fin_wait, value: 30 }
    - { name: net.netfilter.nf_conntrack_max, value: "{{ CONNTRACK_MAX | int }}" }
    - { name: vm.max_map_count, value: 262144 }

